### ISSUE TITLE
Tutorial on How to Use

### ISSUE THREAD

**Issue by havenindustries** [taori/Amusoft.VisualStudio.TemplateGenerator#15] opened 2020-01-07 12:06 UTC
Do you have a writeup or step by step instructions on how to properly use this tool?  The screenshot is nice but it isn't actually working for me.  For instance when I specify a solution it doesn't read anything in from the solution.  I'm assuming this means that I am just not using it correctly.  It builds and starts up fine, I am just not able to get it to do anything.

**Comment by taori** [comment] 2020-01-07 15:58
@havenindustries can you share a screenshot of your configuration? There are a couple of validators in place. Perhaps some validator is missing if nothing is pointing out what is missing for a working configuration

**Comment by havenindustries** [comment] 2020-01-07 17:10
My solution is basically the default Xamarin Forms template.  It seems to not be able to read that.  Basically I select the solution and nothing happens.  Are there some other tools that need to be installed for this to work?

**Comment by havenindustries** [comment] 2020-01-07 17:15
[XamarinApp.zip](https://github.com/taori/Amusoft.VisualStudio.TemplateGenerator/files/4031657/XamarinApp.zip)

**Comment by havenindustries** [comment] 2020-01-07 17:19
![templategenerator](https://user-images.githubusercontent.com/153936/71914631-9d4d2200-313f-11ea-8c62-d4507bfe75f3.png)

**Comment by havenindustries** [comment] 2020-01-07 17:22
I have to say though I LOVE the concept of this and would really like to get it working.  If there is anything I can or should be doing please let me know.

**Comment by taori** [comment] 2020-01-07 17:28
Did you press "+project" on the solution folders? This configuration won't do anything unless you specify a structure of how you want to list a project. I haven't created new configurations lately, so i can't tell for sure if i made it auto insert all projects for new configurations. It certainly needs some more guidance i guess.

You also need to specify output folders - That way your solution will be scaffolded to the given locations.

**Comment by havenindustries** [comment] 2020-01-07 18:03
Interesting .... I assumed it would auto detect the projects.  Do I have to manually add them all and if so why would it need the solution location?  I think it's very possible that I just don't understand what you intended.  My nirvana would be that it reads the solution and populates the projects along with the current folder structure.  I don't mind picking a startup project but if it could detect the currently selected one in the solution that would be great as well.

**Comment by havenindustries** [comment] 2020-01-07 18:06
When I press the +project it also just shows me an empty list am I supposed to type the project name into that textbox?  I think I may have expected it to do more than it does.

**Comment by taori** [comment] 2020-01-07 19:21
> 
> 
> Interesting .... I assumed it would auto detect the projects. Do I have to manually add them all and if so why would it need the solution location? I think it's very possible that I just don't understand what you intended. My nirvana would be that it reads the solution and populates the projects along with the current folder structure. I don't mind picking a startup project but if it could detect the currently selected one in the solution that would be great as well.

Yes, i see what you're getting at. I think i'll just add a dialog who asks the user for autofill when selecting the solution. That should fix this scenario i think. Perhaps there was no message indicating the necessity for the configuration to contain those entries. I'll also insert that too.

**Comment by taori** [comment] 2020-01-07 19:22
> 
> 
> When I press the +project it also just shows me an empty list am I supposed to type the project name into that textbox (actually that's not possible I am pretty sure I am supposed to select one but nothing is there)? I think I may have expected it to do more than it does.

After initial debugging it seems that an older version of MSBuild might be the issue which struggles with newer project types. I'll update the references and check if it works. The project selection should allow to pick all projects references by the solution file.

**Comment by havenindustries** [comment] 2020-01-07 19:43
Awesome!  This is such a great concept!  I truly wish that Microsoft had built this into Visual Studio.  If there is any testing or help I can provide please let me know.  This eventually is going to be a huge timesaver I think (definitely for me).  Great stuff!

**Comment by taori** [comment] 2020-01-07 19:46
You can verify whether it works for you in a bit. Just implementing the mentioned dialog now. Then you can verify whether your solution works as you desire.

And yeah, i think so too. I am surpised that it isn't since there is a growing economy of multi project templates. But hey. At least now there is an alternative compared to doing it manually. Glad you find it useful :)

**Comment by taori** [comment] 2020-01-07 20:22
@havenindustries You can pull from master now and see if it works with the new changes. You might have to clean the solution, but it fixed loading issues i had with my projects (also new project types)

**Comment by havenindustries** [comment] 2020-01-08 01:39
Awesome!  I'll pull it down and test real quick.

**Comment by havenindustries** [comment] 2020-01-08 01:52
When I open up a solution it does prompt me so I have the new version.  However, I end up in the same spot.  I cannot select projects or the startup project (all are blank).  Is there anything else I may need to have installed on my system (developer tools of a certain version, etc)?

**Comment by havenindustries** [comment] 2020-01-08 04:54
The debug output always says 22:50:59.312 DEBUG Validation error SolutionPath: No solution file specified..  Even though the .sln is specified and this happens even for a simple console application.  Any ideas as to what I might be doing wrong?

**Comment by havenindustries** [comment] 2020-01-08 05:17
I haven't dug into why yet but that property for SolutionPath is not getting set or is getting wiped out somehow.  I can see that when the dialog is used the filepath is there but then in all the subsequent calls it simply thinks it is not specified or is null even though it shows in the textbox.  I haven't dug in deep enough yet to see why that is happening.

**Comment by havenindustries** [comment] 2020-01-08 12:12
Basically when a new configuration is created the values of several properties are null.  For one reason or another the properties are getting stuck in a null state.  To get around this I implemented MonkeyCache and modified the property setters/getters and things do load.  It would be good though to get to the bottom of why the properties keep getting set to null.

**Comment by taori** [comment] 2020-01-08 12:14
@havenindustries Yeah. I'll use your zip now and have a look at it myself with your configuration. Maybe i can spot something odd while debugging

**Comment by havenindustries** [comment] 2020-01-08 12:16
@taori for me this behavior happens on every solution even if I just create a basic console app from scratch using the default template.

**Comment by havenindustries** [comment] 2020-01-08 12:20
@taori The only thing I can think of is that you have some valid existing configurations that are setting some of these properties.  Maybe try doing it with no existing valid configurations.

**Comment by havenindustries** [comment] 2020-01-08 12:25
@taori In the temporary fix I put into place I am also checking the setters like SolutionPath to make sure the value isn't null, etc.

**Comment by taori** [comment] 2020-01-08 12:28
> 
> 
> @taori In the temporary fix I put into place I am also checking the setters like SolutionPath to make sure the value isn't null, etc.

That is odd, because i can't reproduce the behavior you are describing.

**Comment by havenindustries** [comment] 2020-01-08 12:30
@taori do you have no valid configurations in your list?  I think that is the key.  If you start from scratch with no existing configurations.  I think you will see this happening. Fingers crossed ...

**Comment by taori** [comment] 2020-01-08 12:42
> 
> 
> @taori do you have no valid configurations in your list? I think that is the key. If you start from scratch with no existing configurations. I think you will see this happening. Fingers crossed ... The first new config you create should trigger the behavior. I also did have several empty new configurations that I deleted.

Are you perhaps always deleting and recreating the configuration to reproduce this behavior? I did use a new configuration but for me the SolutionPath and other values aren't null when i am building the template

**Comment by havenindustries** [comment] 2020-01-08 13:05
@taori No but when I first loaded the app it I had no configurations in the list (as it should). I added a new one and it caused this problem.

**Comment by havenindustries** [comment] 2020-01-08 13:08
So with the small patch I made it is working and producing the zip file in the templates folder but Visual Studio is not recognizing it for some reason.  When I create a new project it is not in the list of templates.

**Comment by taori** [comment] 2020-01-08 13:54
> 
> 
> So with the small patch I made it is working and producing the zip file in the templates folder but Visual Studio is not recognizing it for some reason. When I create a new project it is not in the list of templates. Okay running devenv /installvstemplates fixed that.

Curious. That wasn't required in the past. Perhaps they changed something regarding importing of templates. I know there was some change regarding dotnet templates which i considered adding as feature, since the template format generated by this seems be to be decomissioned at some point, but i certainly don't want to go on relearning how to create templates all the time

**Comment by havenindustries** [comment] 2020-01-08 14:00
@taori the only problem I have right now is that for some reason all of the files in the folder are not being copied for instance that Android.manifest and info.plist for iOS.  Is there some way to specify that we want all files in the project folders?

**Comment by taori** [comment] 2020-01-08 14:04
> 
> 
> @taori the only problem I have right now is that for some reason all of the files in the folder are not being copied for instance that Android.manifest and info.plist for iOS. Is there some way to specify that we want all files in the project folders?

I'll have a look at why this might happen. Perhaps the csproj file does not actively mention them. I'll get back to you in a bit.

**Comment by taori** [comment] 2020-01-08 14:27
@havenindustries ok - please pull the current state and upload the debug log for a "build template" execution. I've added some log lines to print which files are being ignored on purpose.

**Comment by havenindustries** [comment] 2020-01-08 15:10
Is there a way to make it not ignore any files?  That would help a bunch.

**Comment by havenindustries** [comment] 2020-01-08 15:12
I was able to get a functioning template but I had to go and manually export the Android and iOS projects and then manually copy and replace the TemplateContent sections of the generated .vstemplate files for each of those projects.

**Comment by taori** [comment] 2020-01-08 15:40
> 
> 
> Is there a way to make it not ignore any files? That would help a bunch.

Unfortunately not, since the resulting template should be clean and should not contain user/r#/.vs files and other things. Hence some file filtering has to be done



> 
> 
> I was able to get a functioning template but I had to go and manually export the Android and iOS projects and then manually copy and replace the TemplateContent sections of the generated .vstemplate files for each of those projects. <<< All of which is still significantly better than doing all of it by hand.

Mind to share the logs? I want to cover this scenario, because xamarin'ish applications are a common scenario for multi project templates

**Comment by havenindustries** [comment] 2020-01-08 17:09
I can't really use your current code without merging in my changes (otherwise it won't work for me at all).  I'll just try to merge your changes into my current code.

**Comment by taori** [comment] 2020-01-08 17:18
What exactly isn't working then? If you can push a fork that would help a lot. If it works for me then that means there has to be a build dependency installed on my machine that isn't resolved from within the application. I would need to fix that (I use the command line version for CI)

**Comment by havenindustries** [comment] 2020-01-08 17:31
I still would have the original problem with your code where the SolutionPath is stuck in null.  But the good news is that I got everything working and still using the filters.  I only had to change the way the bin and obj folders were being ignored.

**Comment by havenindustries** [comment] 2020-01-08 17:39
Okay the fork is complete https://github.com/havenindustries/Amusoft.VisualStudio.TemplateGenerator I am 99% sure some of those changes aren't necessary but this gets everything working for me.

**Comment by havenindustries** [comment] 2020-01-08 17:40
I think the biggest issue was while ignoring the bin and obj folders sometimes files that both Xamarin Native projects needed were also ignored.

**Comment by taori** [comment] 2020-01-08 18:00
Alright thanks. I'll have a look at it. And yeah - foreign code sometimes needs hacks to just quickly fix things. I'll think of a clean solution :) Thanks for your cooperation though

**Comment by taori** [comment] 2020-01-08 18:07
On first glance your hack breaks multi configuration concepts with alternating solution paths :p Whatever your issue with is needs another fix, or you cannot build more than one solution. Make sure to keep that in mind.

**Comment by havenindustries** [comment] 2020-01-08 18:16
> On first glance your hack breaks multi configuration concepts with alternating solution paths :p Whatever your issue with is needs another fix, or you cannot build more than one solution. Make sure to keep that in mind.

Yep for sure.  I always put my projects together the same way and by default it is how Xamarin does it as well so all of those are fine.  It is most certainly a hack though. :-)

**Comment by havenindustries** [comment] 2020-01-08 18:18
Oh you might be talking about the caching hack.  Yeah, make sure you pick the right one.  I mean that can certainly be fixed.  I should probably do that.

**Comment by havenindustries** [comment] 2020-01-08 18:43
Also the other rule that I am okay with personally is just to never have anything in my bin and obj folders for solutions I want to turn into a template.  That's totally okay with me.

**Comment by havenindustries** [comment] 2020-01-08 18:51
@taori I just tested a second solution and everything worked just fine so I now have two in my configuration.  All good.

**Comment by taori** [comment] 2020-01-08 20:46
Okay - You can pull the current master branch. I found the reason - Xamarin projects do not declare build properties for "BaseOutputPath" unlike some other project types. I would appreciate it if you can verify.

**Comment by havenindustries** [comment] 2020-01-09 11:16
Oh that makes sense! Nice catch!

**Comment by taori** [comment] 2020-01-10 17:29
Closing this as i'd prefer to implement UI in a way where a tutorial isn't really needed and the scope of what the application does isn't that big.

**Closed by taori** 2020-01-10 17:29 UTC
